### ISSUE TITLE
Potential issues with the latest release

### ISSUE THREAD

**Issue by shannonwarren** [NVlabs/curobo#211]
If it’s not a bug, please use discussions: https://github.com/NVlabs/curobo/discussions

Please provide the below information in addition to your issue:

1. cuRobo installation mode (choose from [python, isaac sim, docker python, docker isaac sim]): isaac sim
2. python version:
3. Isaac Sim version (if using): 2022.2.1

------
Issue Details

I'm currently evaluating cuRobo's planner and noticed a performance degradation with the latest release. I used the plan_single_js api on the feb 23rd commit and it works perfectly but it with the latest release it give me an error saying.
`Plan did not converge to a solution.  No action is being taken.` .  My planconfigs were not modified too and my world has no obstacles.

>  goal_js = JointState(
                    position=tensor_args.to_device([-1.588, -1.633, -2.104, -2.324, 1.661, 3.107]),
                    velocity=tensor_args.to_device(sim_js.velocities) * 0.0,
                    acceleration=tensor_args.to_device(sim_js.velocities) * 0.0,
                    jerk=tensor_args.to_device(sim_js.velocities) * 0.0,
                    joint_names=sim_js_names,
                )
                goal_js = goal_js.get_ordered_joint_state(motion_gen.kinematics.joint_names)
                print("Planning to 'home' position")
                print(sim_js.positions)
                result = motion_gen.plan_single_js(
                    cu_js.unsqueeze(0), goal_js.unsqueeze(0), plan_config)
 

>  plan_config = MotionGenPlanConfig(
        enable_graph=False, enable_graph_attempt=8, max_attempts=20, enable_finetune_trajopt=False
    )

**Comment by shannonwarren** [comment]
Additionally, do you have any suggestions on how to debug when there is no plan generated? I know it could it be a resource limitation, MotionGenConfig or PlanConfig or just the collision environment. Is there a way of knowing what's causing this? Thank you

**Comment by balakumar-s** [comment]
Can you share the start_js as well? And is it for the Franka Panda robot?

We have a logger that will create an animated usd of the solver iterations. Though we haven't tested with plan_single_js

Here is an example: https://github.com/NVlabs/curobo/blob/774dcfd609847ad98147f166ea2f5954516ff7a0/examples/usd_example.py#L168

**Comment by shannonwarren** [comment]
I'm using a ur5e robot in sim. I've made some changes to constraint_reacher.py to use both plan_single_js and plan_single 
```
import torch

a = torch.zeros(4, device="cuda:0")
from omni.isaac.kit import SimulationApp

simulation_app = SimulationApp(
    {
        "headless": False,
        "width": "1920",
        "height": "1080",
    }
)
import numpy as np
import torch
from helper import add_extensions, add_robot_to_scene

from curobo.geom.sdf.world import CollisionCheckerType
from curobo.geom.types import Cuboid, WorldConfig
from curobo.types.base import TensorDeviceType
from curobo.types.math import Pose
from curobo.types.robot import JointState, RobotConfig
from curobo.types.state import JointState
from curobo.util_file import get_robot_configs_path, get_world_configs_path, join_path, load_yaml
from curobo.wrap.model.robot_world import RobotWorld, RobotWorldConfig
from curobo.wrap.reacher.motion_gen import (
    MotionGen,
    MotionGenConfig,
    MotionGenPlanConfig,
    PoseCostMetric,
)

simulation_app.update()
import argparse

import carb
from omni.isaac.core import World
from omni.isaac.core.materials import OmniGlass, OmniPBR
from omni.isaac.core.objects import cuboid, sphere
from omni.isaac.core.utils.types import ArticulationAction

from curobo.util.usd_helper import UsdHelper

parser = argparse.ArgumentParser()


parser.add_argument("--robot", type=str, default="ur5e.yml", help="robot configuration to load")
parser.add_argument(
    "--visualize_spheres",
    action="store_true",
    help="When True, visualizes robot spheres",
    default=True,
)


args = parser.parse_args()


def create_environment():
    # world_cfg1 = 
    pass


if __name__ == "__main__":
    my_world = World(stage_units_in_meters=1.0)
    stage = my_world.stage
    n_obstacle_cuboids = 10
    n_obstacle_mesh = 10

    stage = my_world.stage
    # my_world.scene.add_default_ground_plane()

    xform = stage.DefinePrim("/World", "Xform")
    stage.SetDefaultPrim(xform)
    target_material = OmniPBR("/World/looks/t", color=np.array([0, 1, 0]))
    target_material_2 = OmniPBR("/World/looks/t2", color=np.array([0, 1, 0]))
    target_material_plane = OmniGlass(
        "/World/looks/t3", color=np.array([0, 1, 0]), ior=1.25, depth=0.001, thin_walled=False
    )
    target_material_line = OmniGlass(
        "/World/looks/t4", color=np.array([0, 1, 0]), ior=1.25, depth=0.001, thin_walled=True
    )

    # target_orient = [0,0,0.707,0.707]
    # target_orient = [0.5, -0.5, 0.5, 0.5]
    target_orient = [0.5, -0.5, 0.5, -0.5]
    # target_orient = [0, 0, 0, 1]
    dropoff_orient = [-0.5, 0.5, 0.5, -0.5]

    # Make a target to follow
    target = cuboid.VisualCuboid(
        "/World/target_1",
        position=np.array([0.15, 0.35, 0.35]),
        orientation=np.array(target_orient),
        size=0.02,
        visual_material=target_material,
    )

    # Make a target to follow
    target_2 = cuboid.VisualCuboid(
        "/World/target_2",
        position=np.array([0.10, 0.35, 0.5]),
        orientation=np.array(target_orient),
        size=0.02,
        visual_material=target_material_2,
    )

    target_3 = cuboid.VisualCuboid(
        "/World/target_3",
        position=np.array([0.45, 0.35, 0.291]),
        orientation=np.array(target_orient),
        size=0.02,
        visual_material=target_material_2,
    )

    target_4 = cuboid.VisualCuboid(
        "/World/target_4",
        position=np.array([-0.2, 0.35, 0.291]),
        orientation=np.array(dropoff_orient),
        size=0.02,
        visual_material=target_material_2,
    )

    target_5 = cuboid.VisualCuboid(
        "/World/target_5",
        position=np.array([-0.5, 0.35, 0.291]),
        orientation=np.array(dropoff_orient),
        size=0.02,
        visual_material=target_material_2,
    )

    target_6 = cuboid.VisualCuboid(
        "/World/target_6",
        position=np.array([-0.5, 0.35, 0.291]),
        orientation=np.array(dropoff_orient),
        size=0.02,
        visual_material=target_material_2,
    )

    # x_plane = cuboid.VisualCuboid(
    #     "/World/constraint_plane",
    #     position=np.array([0.55, 0.05, 0.5]),
    #     orientation=np.array(target_orient),
    #     scale=[1.1, 0.001, 1.0],
    #     visual_material=target_material_plane,
    # )
    # xz_line = cuboid.VisualCuboid(
    #     "/World/constraint_line",
    #     position=np.array([0.55, 0.05, 0.5]),
    #     orientation=np.array(target_orient),
    #     scale=[0.04, 0.04, 0.65],
    #     visual_material=target_material_line,
    # )

    collision_checker_type = CollisionCheckerType.BLOX

    tensor_args = TensorDeviceType()

    robot_cfg = load_yaml(join_path(get_robot_configs_path(), args.robot))["robot_cfg"]

    j_names = robot_cfg["kinematics"]["cspace"]["joint_names"]
    default_config = robot_cfg["kinematics"]["cspace"]["retract_config"]

    robot, robot_prim_path = add_robot_to_scene(robot_cfg, my_world, "/World/world_robot/")

    world_cfg_table = WorldConfig.from_dict(
        load_yaml(join_path(get_world_configs_path(), "collision_wall.yml"))
    )

    # world_cfg_table.cuboid[0].pose[2] -= 0.01
    world_cfg1 = WorldConfig.from_dict(
        load_yaml(join_path(get_world_configs_path(), "p5_basic_env.yml"))
    )

    world_cfg = WorldConfig(cuboid=world_cfg1.cuboid)

    usd_help = UsdHelper()

    enable_debug=False
    usd_help.load_stage(my_world.stage)
    usd_help.add_world_to_stage(world_cfg.get_mesh_world(), base_frame="/World")
    motion_gen_config = MotionGenConfig.load_from_robot_config(
        robot_cfg,
        world_cfg,
        tensor_args,
        trajopt_tsteps=40,
        collision_checker_type=CollisionCheckerType.MESH,
        use_cuda_graph=True,
        num_trajopt_seeds=12,
        num_graph_seeds=12,
        interpolation_dt=0.03,
        collision_cache={"obb": n_obstacle_cuboids},
        collision_activation_distance=0.025,
        acceleration_scale=1.0,
        fixed_iters_trajopt=True,
        store_ik_debug=enable_debug,
        store_trajopt_debug=enable_debug,
    )
    motion_gen = MotionGen(motion_gen_config)
    print("warming up..")
    motion_gen.warmup(warmup_js_trajopt=True)

    world_model = motion_gen.world_collision

    i = 0
    tensor_args = TensorDeviceType()
    target_list = [target_2, target, target_3, target, target_4, target_5, target_6]
    target_material_list = [target_material, target_material_2]
    for material in target_material_list:
        material.set_color(np.array([0.1, 0.1, 0.1]))
    target_material_plane.set_color(np.array([1, 1, 1]))
    target_material_line.set_color(np.array([1, 1, 1]))

    target_idx = 0
    cmd_idx = 0
    cmd_plan = None
    articulation_controller = robot.get_articulation_controller()
    plan_config = MotionGenPlanConfig(
        enable_graph=False, enable_graph_attempt=8, max_attempts=20, enable_finetune_trajopt=False
    )

    plan_idx = 0
    cmd_step_idx = 0
    pose_cost_metric = None
    spheres = None
    while simulation_app.is_running():
        my_world.step(render=True)

        if not my_world.is_playing():
            if i % 100 == 0:
                print("**** Click Play to start simulation *****")
            i += 1
            # if step_index == 0:
            #    my_world.play()
            continue
        step_index = my_world.current_time_step_index

        if step_index <= 2:
            my_world.reset()
            idx_list = [robot.get_dof_index(x) for x in j_names]

            # default_config = [1.5127, -1.8392, 1.87056, -0.1426, 3.15, 3.1165]
            default_config = [-1.588, -1.633, -2.104, -2.324, 1.661, 3.107]
            robot.set_joint_positions(default_config, idx_list)

            robot._articulation_view.set_max_efforts(
                values=np.array([5000 for i in range(len(idx_list))]), joint_indices=idx_list
            )
        

        if False and step_index % 50 == 0.0:  # No obstacle update
            obstacles = usd_help.get_obstacles_from_stage(
                # only_paths=[obstacles_path],
                reference_prim_path=robot_prim_path,
                ignore_substring=[
                    robot_prim_path,
                    "/World/target",
                    "/World/target_2",
                    "/World/target_3",
                    "/World/defaultGroundPlane",
                    "/curobo",
                ],
            ).get_collision_check_world()
            # print(len(obstacles.objects))

            motion_gen.update_world(obstacles)
            # print("Updated World")
            carb.log_info("Synced CuRobo world from stage.")

        linear_color = np.ravel([249, 87, 56]) / 255.0
        orient_color = np.ravel([103, 148, 54]) / 255.0

        disable_color = np.ravel([255, 255, 255]) / 255.0

        if cmd_plan is None and step_index % 10 == 0:

            if plan_idx == 4:
                print("Constrained: Holding tool linear-y")
                pose_cost_metric = PoseCostMetric(
                    hold_partial_pose=True,
                    hold_vec_weight=motion_gen.tensor_args.to_device([0, 0, 0, 0, 1, 0]),
                )
                # target_material_plane.set_color(linear_color)
            if plan_idx == 8:
                print("Constrained: Holding tool Orientation and linear-y")
                pose_cost_metric = PoseCostMetric(
                    hold_partial_pose=True,
                    hold_vec_weight=motion_gen.tensor_args.to_device([1, 1, 1, 0, 1, 0]),
                )
                # target_material_plane.set_color(orient_color)
            if plan_idx == 12:
                print("Constrained: Holding tool linear-y, linear-x")
                pose_cost_metric = PoseCostMetric(
                    hold_partial_pose=True,
                    hold_vec_weight=motion_gen.tensor_args.to_device([0, 0, 0, 1, 1, 0]),
                )
                # target_material_line.set_color(linear_color)
                # target_material_plane.set_color(disable_color)

            if target_idx == 5 or target_idx == 2:
                # print("Constrained: Holding tool Orientation and linear-y, linear-x")
                # pose_cost_metric = PoseCostMetric(
                #     hold_partial_pose=True,
                #     hold_vec_weight=motion_gen.tensor_args.to_device([1, 1, 1, 1, 1, 0]),
                # )
                
                pose_cost_metric = PoseCostMetric(
                    hold_partial_pose=False,
                    hold_vec_weight=motion_gen.tensor_args.to_device([0, 0, 0, 1, 1, 0]),
                )
                # target_material_line.set_color(orient_color)
                # target_material_plane.set_color(disable_color)
            else:
                pose_cost_metric = None

            if plan_idx > 20:
                plan_idx = 0

            if plan_idx == 0:
                print("Constrained: Reset")
                # target_material_line.set_color(disable_color)
                # target_material_plane.set_color(disable_color)

                pose_cost_metric = None

            # plan_config.pose_cost_metric = pose_cost_metric

            # motion generation:
            for ks in range(len(target_material_list)):
                if ks == target_idx:
                    target_material_list[ks].set_color(np.ravel([0, 1.0, 0]))
                else:
                    target_material_list[ks].set_color(np.ravel([0.1, 0.1, 0.1]))

            sim_js = robot.get_joints_state()
            sim_js_names = robot.dof_names
            cu_js = JointState(
                position=tensor_args.to_device(sim_js.positions),
                velocity=tensor_args.to_device(sim_js.velocities) * 0.0,
                acceleration=tensor_args.to_device(sim_js.velocities) * 0.0,
                jerk=tensor_args.to_device(sim_js.velocities) * 0.0,
                joint_names=sim_js_names,
            )
            cu_js = cu_js.get_ordered_joint_state(motion_gen.kinematics.joint_names)


            if args.visualize_spheres:
                sph_list = motion_gen.kinematics.get_robot_as_spheres(cu_js.position)
                if spheres is None:
                    spheres = []
                    # create spheres:

                    for si, s in enumerate(sph_list[0]):
                        sp = sphere.VisualSphere(
                            prim_path="/curobo/robot_sphere_" + str(si),
                            position=np.ravel(s.position),
                            radius=float(s.radius),
                            color=np.array([0, 0.8, 0.2]),
                        )
                        spheres.append(sp)
                else:
                    for si, s in enumerate(sph_list[0]):
                        spheres[si].set_world_pose(position=np.ravel(s.position))
                        spheres[si].set_radius(float(s.radius))
            # target_idx = 1
            # if target_idx == 0:
            #     cube_position, cube_orientation = target_list[target_idx].get_world_pose()
            #     # Set EE teleop goals, use cube for simple non-vr init:
            #     ee_translation_goal = cube_position
            #     # ee_translation_goal[0] -= 0.05
            #     print(f"Cube position: {cube_position}")
            #     ee_orientation_teleop_goal = cube_orientation

            #     # compute curobo solution:
            #     ik_goal = Pose(
            #         position=tensor_args.to_device(ee_translation_goal),
            #         quaternion=tensor_args.to_device(ee_orientation_teleop_goal),
            #     )
            #     result = motion_gen.plan_single(cu_js.unsqueeze(0), ik_goal, plan_config)
            #     # ik_result = ik_solver.solve_single(ik_goal, cu_js.position.view(1,-1), cu_js.position.view(1,1,-1))
            # if target_idx == 0:
            #     goal_js = JointState(
            #         position=tensor_args.to_device([1.5127, -1.8392, 1.87056, -0.1426, 2.65, 3.107]),
            #         velocity=tensor_args.to_device(sim_js.velocities) * 0.0,
            #         acceleration=tensor_args.to_device(sim_js.velocities) * 0.0,
            #         jerk=tensor_args.to_device(sim_js.velocities) * 0.0,
            #         joint_names=sim_js_names,
            #     )
            #     goal_js = goal_js.get_ordered_joint_state(motion_gen.kinematics.joint_names)
            #     print("Planning to 'home' position")
            #     result = motion_gen.plan_single_js(
            #         cu_js.unsqueeze(0), goal_js.unsqueeze(0), plan_config)

            # [-0.46550992, -1.954953, -1.623367, -2.704879, -2.0370042, 3.1413608]
            # [-0.46607167, -2.2323098, -1.7905357, -5.44564, -4.242987, 6.1823845 ]
            if target_idx == 6:
                goal_js = JointState(
                    position=tensor_args.to_device([-1.588, -1.633, -2.104, -2.324, 1.661, 3.107]),
                    velocity=tensor_args.to_device(sim_js.velocities) * 0.0,
                    acceleration=tensor_args.to_device(sim_js.velocities) * 0.0,
                    jerk=tensor_args.to_device(sim_js.velocities) * 0.0,
                    joint_names=sim_js_names,
                )
                goal_js = goal_js.get_ordered_joint_state(motion_gen.kinematics.joint_names)
                print("Planning to 'home' position")
                # print(plan_config)
                # print(goal_js)
                print(sim_js.positions)
                result = motion_gen.plan_single_js(
                    cu_js.unsqueeze(0), goal_js.unsqueeze(0), plan_config)

            else:
                cube_position, cube_orientation = target_list[target_idx].get_world_pose()
                # Set EE teleop goals, use cube for simple non-vr init:
                ee_translation_goal = cube_position
                ee_orientation_teleop_goal = cube_orientation

                # compute curobo solution:
                ik_goal = Pose(
                    position=tensor_args.to_device(ee_translation_goal),
                    quaternion=tensor_args.to_device(ee_orientation_teleop_goal),
                )
                start_state = cu_js.unsqueeze(0)
                # link_chain = motion_gen.kinematics.kinematics_config.link_chain_map[
                #     motion_gen.kinematics.kinematics_config.store_link_map.to(dtype=torch.long)
                # ]
                # link_poses = state.link_pose

                result = motion_gen.plan_single(cu_js.unsqueeze(0), ik_goal, plan_config)
                UsdHelper.write_motion_gen_log(
                    result,
                    robot_cfg,
                    world_cfg,
                    start_state,
                    ik_goal,
                    join_path("log/usd/", "debug"),
                    write_robot_usd_path=join_path("log/usd/", "debug/assets/"),
                    write_ik=False,
                    write_trajopt=False,
                    visualize_robot_spheres=False,
                    grid_space=2,
                    # link_poses=link_poses,
                )

            print(f"Status: {result.status} | Success?: {result.success} | valid_query?: {result.valid_query} | debug_info: {result.debug_info}")
            print(f"Solve time: {result.solve_time} | IK time: {result.ik_time} | Graph time: {result.graph_time} | Trajopt time: {result.trajopt_time} | Finetune time: {result.finetune_time} | Total time: {result.total_time}")
            succ = result.success.item()  # ik_result.success.item()
            plan_idx += 1
            if succ:
                cmd_plan = result.get_interpolated_plan()
                cmd_plan = motion_gen.get_full_js(cmd_plan)
                # get only joint names that are in both:
                idx_list = []
                common_js_names = []
                for x in sim_js_names:
                    if x in cmd_plan.joint_names:
                        idx_list.append(robot.get_dof_index(x))
                        common_js_names.append(x)
                # idx_list = [robot.get_dof_index(x) for x in sim_js_names]

                cmd_plan = cmd_plan.get_ordered_joint_state(common_js_names)

                cmd_idx = 0
                target_idx += 1
                if target_idx >= len(target_list):
                    target_idx = 0

            else:
                carb.log_warn("Plan did not converge to a solution.  No action is being taken.")
        if cmd_plan is not None:
            cmd_state = cmd_plan[cmd_idx]

            # get full dof state
            art_action = ArticulationAction(
                cmd_state.position.cpu().numpy(),
                cmd_state.velocity.cpu().numpy(),
                joint_indices=idx_list,
            )
            # set desired joint angles obtained from IK:
            articulation_controller.apply_action(art_action)
            cmd_step_idx += 1
            if cmd_step_idx == 2:
                cmd_idx += 1
                cmd_step_idx = 0
            # for _ in range(2):
            #    my_world.step(render=False)
            if cmd_idx >= len(cmd_plan.position):
                cmd_idx = 0
                cmd_plan = None
    print("finished program")

    simulation_app.close()

```

**Comment by shannonwarren** [comment]
This is what i have running in sim. when `target_idx == 6` I tell the robot to go home using the joint state api and it fails to plan.
[Screencast from 04-08-2024 12:56:47 PM.webm](https://github.com/NVlabs/curobo/assets/46359438/0329c8c2-1bae-40e2-88d4-827243d71537)

**Comment by shannonwarren** [comment]
@balakumar-s I just tried the simple_stacking.py isaac example which has the usdhelper calling write_motion_gen_log api and switched on the save_log flag to True and i get this error.

> [7.206s] Simulation App Startup Complete
> warming up...
> Traceback (most recent call last):
>   File "examples/isaac_sim/simple_stacking.py", line 435, in <module>
>     my_world=my_world, my_task=my_task, constrain_grasp_approach=args.constrain_grasp_approach
>   File "examples/isaac_sim/simple_stacking.py", line 161, in __init__
>     self.motion_gen.warmup(parallel_finetune=True)
>   File "curobo/src/curobo/wrap/reacher/motion_gen.py", line 2202, in warmup
>     self.plan_single_js(start_state, goal_state, MotionGenPlanConfig(max_attempts=1))
>   File "curobo/src/curobo/wrap/reacher/motion_gen.py", line 2372, in plan_single_js
>     solve_state, start_state, goal_state, plan_config=plan_config
>   File "curobo/src/curobo/wrap/reacher/motion_gen.py", line 1842, in _plan_js_from_solve_state
>     result.debug_info["trajopt_result"] = traj_result
> TypeError: 'NoneType' object does not support item assignment
> 2024-04-08 20:54:16 [14,746ms] [Warning] [carb.audio.context] 1 contexts were leaked
> /home/shannon/.local/share/ov/pkg/isaac_sim-2022.2.1/python.sh: line 41: 593397 Segmentation fault      (core dumped) $python_exe "$@" $args
> There was an error running python

**Comment by shannonwarren** [comment]
An update on 2) regarding navigating to the two joint states. There was a self collision in my tool joint causing the failure to plan. I reduced the sphere size to a very low value and it works reliably. I think I'll need to add this to the `self_collision_ignore`. Would be helpful to see a debug message when self collision happens.

**Comment by balakumar-s** [comment]
We have joint space planner working better in the latest release. Let us know if you have issues.
