### ISSUE TITLE
Installing Curobo

### ISSUE THREAD

**Issue by GeorgeBethel** [NVlabs/curobo#282]
I am installing curobo using the link below

https://curobo.org/get_started/1_install_instructions.html

I get the error below

pip install -e . --no-build-isolation
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///home/george/curobo
  Checking if build backend supports build_editable ... done
  Preparing editable metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/home/george/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/george/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/george/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 181, in prepare_metadata_for_build_editable
          return hook(metadata_directory, config_settings)
        File "/home/george/.local/lib/python3.10/site-packages/setuptools/build_meta.py", line 453, in prepare_metadata_for_build_editable
          return self.prepare_metadata_for_build_wheel(
        File "/home/george/.local/lib/python3.10/site-packages/setuptools/build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/home/george/.local/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 22, in <module>
        File "/home/george/.local/lib/python3.10/site-packages/torch/__init__.py", line 237, in <module>
          from torch._C import *  # noqa: F403
      ImportError: libcudnn.so.8: cannot open shared object file: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

My device spec is
- Dell precision
- Nvidia GeForce RTX 2000
- nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Thu_Mar_28_02:18:24_PDT_2024
Cuda compilation tools, release 12.4, V12.4.131
Build cuda_12.4.r12.4/compiler.34097967_0

**Comment by blooop** [comment]
On 22.04 I did:
sudo apt install cuda-nvcc-11-8
pip3 install torch==2.2.1 --index-url https://download.pytorch.org/whl/cu118
