### ISSUE TITLE
Error while running torch_layers_example.py

### ISSUE THREAD

**Issue by jeonsuhyun** [NVlabs/curobo#304]
I am having problem with example code 'torch_layers_example.py'
My environment is Ubuntu20.04, python 3.10.14 pytorch 2.3.1 cuda 11.8 on conda.

While i was running the example code, this error occurred, and I tried to figure it out, but i couldn't.

Traceback (most recent call last):
  File "/home/suhyun/curobo/examples/torch_layers_example.py", line 169, in <module>
    loss.backward()
  File "/home/suhyun/anaconda3/envs/curobo/lib/python3.10/site-packages/torch/_tensor.py", line 525, in backward
    torch.autograd.backward(
  File "/home/suhyun/anaconda3/envs/curobo/lib/python3.10/site-packages/torch/autograd/__init__.py", line 267, in backward
    _engine_run_backward(
  File "/home/suhyun/anaconda3/envs/curobo/lib/python3.10/site-packages/torch/autograd/graph.py", line 744, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function PoseErrorBackward returned an invalid gradient at index 0 - got [512, 1, 3] but expected shape compatible with [512, 1, 1, 3]

How can i fix this error?
Thanks.

**Comment by balakumar-s** [comment]
Thanks! This has been fixed in latest main.
