### ISSUE TITLE
Issue in installation with setuptools 70

### ISSUE THREAD

**Issue by mcaniot** [NVlabs/curobo#315]
I tried to install on a virtual environment but I got an error with the setuptools 70.1.1. When i downgrade to 69 the installation work well. Do you have the same issue ? the version of curobo is 0.7.3 but the issue is the same with 0.6.2

```
error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "/home/install/sim/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/install/sim/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/install/sim/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/home/install/sim/lib/python3.10/site-packages/setuptools/build_meta.py", line 368, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/home/install/sim/lib/python3.10/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 22, in <module>
        File "/home/install/sim/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 25, in <module>
          from pkg_resources import packaging  # type: ignore[attr-defined]
      ImportError: cannot import name 'packaging' from 'pkg_resources' (/home/install/sim/lib/python3.10/site-packages/pkg_resources/__init__.py)

```

**Comment by balakumar-s** [comment]
We don't directly use `pkg_resources`. This is related to pytorch: https://github.com/pytorch/serve/issues/3176
