### ISSUE TITLE
curobo failed to parse urdf

### ISSUE THREAD

**Issue by DuYi-angle** [NVlabs/curobo#370]
If it’s not a bug, please use discussions: https://github.com/NVlabs/curobo/discussions

Please provide the below information in addition to your issue:

1. cuRobo installation mode (choose from [python, isaac sim, docker python, docker isaac sim]):isaac sim
2. python version:3.8
3. Isaac Sim version (if using): 4.0.0

------
Issue Details:
I'm following curobo's configure a new robot tutorial to configure my own robot, here's my relevant config file:
[rm_description.zip](https://github.com/user-attachments/files/16622065/rm_description.zip)
[rm_65.zip](https://github.com/user-attachments/files/16622076/rm_65.zip)

I followed Franka's example to store my files，but when I change the franka.yml in the motion_gen_reacher.py to rm_65.yml and run the example, the terminal shows：
##
Failed to load '/home/muray/curobo/src/curobo/content/assets/robot/rm_descripton/rm_65.urdf'2024-08-15 06:28:59 [11,173ms] [Error] [omni.importer.urdf] Failed to parse URDF file 'rm_65.urdf'
2024-08-15 06:28:59 [11,173ms] [Warning] [omni.importer.urdf] Cannot add robot to stage, number of links is zero

Traceback (most recent call last):
  File "/home/muray/curobo/examples/isaac_sim/motion_gen_reacher.py", line 444, in <module>
    main()
  File "/home/muray/curobo/examples/isaac_sim/motion_gen_reacher.py", line 190, in main
    robot, robot_prim_path = add_robot_to_scene(robot_cfg, my_world)
  File "/home/muray/curobo/examples/isaac_sim/helper.py", line 113, in add_robot_to_scene
    robot_p = Robot(
  File "/home/muray/.local/share/ov/pkg/isaac-sim-4.0.0/exts/omni.isaac.core/omni/isaac/core/robots/robot.py", line 73, in __init__
    Articulation.__init__(
  File "/home/muray/.local/share/ov/pkg/isaac-sim-4.0.0/exts/omni.isaac.core/omni/isaac/core/articulations/articulation.py", line 105, in __init__
    self._articulation_view = ArticulationView(
  File "/home/muray/.local/share/ov/pkg/isaac-sim-4.0.0/exts/omni.isaac.core/omni/isaac/core/articulations/articulation_view.py", line 117, in __init__
    XFormPrimView.__init__(
  File "/home/muray/.local/share/ov/pkg/isaac-sim-4.0.0/exts/omni.isaac.core/omni/isaac/core/prims/xform_prim_view.py", line 132, in __init__
    raise Exception(
Exception: Prim path expression /base_link is invalid, a prim matching the expression needs to created before wrapping it as view
##

It's not clear to me why my urdf parsing fails, it's no problem to look at the file with ROS's urdf checker tool.Can someone help me with this？

**Comment by DuYi-angle** [comment]
I found out that it was a typo and the issue will be closed
