### ISSUE TITLE
curobo/examples/isaac_sim/mpc_example.py can not run in isaac-sim 4.1.0-rc.7+

### ISSUE THREAD

**Issue by xialuanshi** [NVlabs/curobo#377]
If it’s not a bug, please use discussions: https://github.com/NVlabs/curobo/discussions

Please provide the below information in addition to your issue:

1. cuRobo installation mode (choose from [python, isaac sim, docker python, docker isaac sim]):docker isaac sim
2. python version:Python 3.10.14(isaac-sim python)
3. Isaac Sim version (if using): isaac-sim 4.1.0-rc.7+

------
Issue Details
when i run script /isaac-sim/python.sh examples/isaac_sim/mpc_example.py,then give me the problem "Traceback (most recent call last):
  File "/workspace/curobo/examples/isaac_sim/mpc_example.py", line 377, in <module>
    main()
  File "/workspace/curobo/examples/isaac_sim/mpc_example.py", line 368, in main
    articulation_controller.apply_action(art_action)
  File "/isaac-sim/exts/omni.isaac.core/omni/isaac/core/controllers/articulation_controller.py", line 64, in apply_action
    if joint_positions[0][i] is None or np.isnan(
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()",any solution here?

**Comment by balakumar-s** [comment]
This has been fixed in the latest release.
