### ISSUE TITLE
No NVIDIA driver on your system inside docker in AGX Jetson!

### ISSUE THREAD

**Issue by sarthak-ies** [NVlabs/curobo#405]
I have been using `aarch.dockerfile` to run the curobo container, and while running the [forward_kinematics](https://curobo.org/get_started/2a_python_examples.html#forward-kinematics) script, it throws me this error!

Architecture - aarch64
Linux - Ubuntu 22.04
Hardware - Jetson AGX

```
root@ros1-docker:/pkgs# python3 forward_kinematics.py 
Traceback (most recent call last):
  File "forward_kinematics.py", line 25, in <module>
    robot_cfg = RobotConfig.from_basic(urdf_file, base_link, ee_link, tensor_args)
  File "/usr/local/lib/python3.8/dist-packages/curobo/types/robot.py", line 58, in from_basic
    cuda_robot_model_config = CudaRobotModelConfig.from_basic_urdf(
  File "/usr/local/lib/python3.8/dist-packages/curobo/cuda_robot_model/cuda_robot_model.py", line 125, in from_basic_urdf
    return CudaRobotModelConfig.from_config(config)
  File "/usr/local/lib/python3.8/dist-packages/curobo/cuda_robot_model/cuda_robot_model.py", line 248, in from_config
    generator = CudaRobotGenerator(config)
  File "/usr/local/lib/python3.8/dist-packages/curobo/cuda_robot_model/cuda_robot_generator.py", line 260, in __init__
    self.initialize_tensors()
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/curobo/cuda_robot_model/cuda_robot_generator.py", line 285, in initialize_tensors
    self._link_spheres_tensor = torch.empty(
  File "/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py", line 217, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

```

**Comment by balakumar-s** [comment]
We have simplified the installation of curobo. It will now only require a python environment that has pytorch already installed. Follow instructions here for installing pytorch on a Jetson: https://docs.nvidia.com/deeplearning/frameworks/install-pytorch-jetson-platform/index.html
