### ISSUE TITLE
mpc_nvblox_example.py runs into an ValueError with it's ArticulationController

### ISSUE THREAD

**Issue by Bradan** [NVlabs/curobo#444]
If it’s not a bug, please use discussions: https://github.com/NVlabs/curobo/discussions

Please provide the below information in addition to your issue:

1. cuRobo installation mode (choose from [python, isaac sim, docker python, docker isaac sim]): isaac sim
2. python version: Python 3.10.14
3. Isaac Sim version (if using): 4.2.0

------
Issue Details

When trying to run the mpc_nvblox_example.py it crashes with an exception:

```
Traceback (most recent call last):
  File "/home/user/curobo/examples/isaac_sim/mpc_nvblox_example.py", line 341, in main
    articulation_controller.apply_action(art_action)
  File "/home/user/.local/share/ov/pkg/isaac-sim-4.2.0/exts/omni.isaac.core/omni/isaac/core/controllers/articulation_controller.py", line 64, in apply_action
    if joint_positions[0][i] is None or np.isnan(
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

As the exception says it can be fixed by .any() behind the np.isnan calls in line 66 and 75 of the file exts/omni.isaac.core/omni/isaac/core/controllers/articulation_controller.py, but I cannot find this file in any public repository.

I was tempted to post this in https://github.com/isaac-sim/IsaacLab, but maybe I'm just solving it too deep inside Isaac Sim and there's actually a fix inside cuRobo to make this a scalar value?

**Comment by balakumar-s** [comment]
We have fixed this in the latest release (v0.7.7).
