### ISSUE TITLE
ModuleNotFoundError: No module named 'pxr'

### ISSUE THREAD

**Issue by pmj110119** [NVlabs/curobo#62]
If it’s not a bug, please use discussions: https://github.com/NVlabs/curobo/discussions

Please provide the below information in addition to your issue:

1. cuRobo installation mode (choose from [python, isaac sim, docker python, docker isaac sim]):    python
2. python version:    python==3.7
3. Isaac Sim version (if using):   not used

------
Issue Details

I need help, thanks!!!!!

$ python examples/motion_gen_api_example.py

Traceback (most recent call last):
  File "examples/motion_gen_api_example.py", line 20, in <module>
    from curobo.util.usd_helper import UsdHelper
  File "/home/panmingjie/gsnet/curobo/src/curobo/util/usd_helper.py", line 19, in <module>
    from pxr import Gf, Sdf, Usd, UsdGeom, UsdPhysics, UsdShade
ModuleNotFoundError: No module named 'pxr'

**Comment by balakumar-s** [comment]
Install usd-core with `pip install usd-core`
